# Generated by Django 4.2.17 on 2025-03-18 07:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthNews",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("tag_id", models.IntegerField()),
                ("cover", models.CharField(max_length=255)),
                ("reader_ids", models.JSONField()),
                ("is_top", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "news",
            },
        ),
        migrations.CreateModel(
            name="HealthData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("weight", models.FloatField()),
                ("sleep_hours", models.FloatField()),
                ("exercise_time", models.IntegerField()),
                ("feedback", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.sysuser",
                    ),
                ),
            ],
            options={
                "db_table": "health_data",
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("replier_id", models.IntegerField(blank=True, null=True)),
                ("content_type", models.CharField(max_length=50)),
                ("parent_id", models.IntegerField(blank=True, null=True)),
                ("content_id", models.IntegerField()),
                ("content", models.TextField()),
                ("upvote_list", models.JSONField(blank=True, default=list)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "commenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.sysuser"
                    ),
                ),
            ],
            options={
                "db_table": "evaluations",
                "ordering": ["-create_time"],
            },
        ),
    ]
