# Generated by Django 4.1 on 2025-04-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthdata",
            name="calories_burned",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="healthdata",
            name="exercise_count",
            field=models.IntegerField(default=0),
        ),
    ]
