# Generated by Django 4.2.20 on 2025-05-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthview", "0002_healthdata_calories_burned_healthdata_exercise_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthdata",
            name="calories_burned",
        ),
        migrations.RemoveField(
            model_name="healthdata",
            name="exercise_count",
        ),
        migrations.AddField(
            model_name="healthdata",
            name="exercise_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="healthdata",
            name="feedback",
            field=models.CharField(max_length=200),
        ),
    ]
