# Generated by Django 4.2.20 on 2025-05-06 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalorieRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("exercise_type", models.CharField(max_length=50)),
                ("weight", models.FloatField()),
                ("counter", models.IntegerField()),
                ("calories", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.sysuser",
                    ),
                ),
            ],
        ),
    ]
