# Generated by Django 4.2.20 on 2025-05-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="calorierecord",
            table="fitness_calorierecord",
        ),
    ]
