# Generated by Django 4.2.20 on 2025-05-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0002_alter_calorierecord_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calorierecord",
            old_name="user_id",
            new_name="user",
        ),
    ]
