# Generated by Django 4.2.20 on 2026-05-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("fitness", "0003_rename_user_id_calorierecord_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="DanceStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="舞蹈名称")),
                (
                    "dance_type",
                    models.CharField(max_length=50, verbose_name="舞蹈类型"),
                ),
                (
                    "video_path",
                    models.CharField(max_length=255, verbose_name="标准视频路径"),
                ),
                (
                    "keypoints_data",
                    models.TextField(
                        blank=True, null=True, verbose_name="关键点序列JSON"
                    ),
                ),
                ("duration", models.FloatField(default=0, verbose_name="时长(秒)")),
                (
                    "difficulty",
                    models.IntegerField(default=1, verbose_name="难度等级(1-5)"),
                ),
                ("fps", models.FloatField(default=30, verbose_name="视频帧率")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="舞蹈描述"),
                ),
                (
                    "thumbnail",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="封面图路径"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fitness_dance_standard",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DanceScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_video_path",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="用户视频路径",
                    ),
                ),
                (
                    "total_score",
                    models.FloatField(default=0, verbose_name="总分(0-100)"),
                ),
                (
                    "accuracy_score",
                    models.FloatField(default=0, verbose_name="准确度得分"),
                ),
                ("rhythm_score", models.FloatField(default=0, verbose_name="节奏得分")),
                (
                    "fluency_score",
                    models.FloatField(default=0, verbose_name="流畅度得分"),
                ),
                (
                    "frame_similarity",
                    models.TextField(
                        blank=True, null=True, verbose_name="每帧相似度JSON"
                    ),
                ),
                (
                    "dance_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="舞蹈名称"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dance_standard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitness.dancestandard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.sysuser",
                    ),
                ),
            ],
            options={
                "db_table": "fitness_dance_score",
                "ordering": ["-created_at"],
            },
        ),
    ]
