# Generated by Django 4.2.20 on 2026-05-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("fitness", "0005_dance_angle_standards"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoProcessTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("preprocess", "预处理"), ("evaluate", "评分")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, help_text="处理进度 0-100"),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, help_text="状态消息", max_length=200, null=True
                    ),
                ),
                (
                    "result_data",
                    models.TextField(blank=True, help_text="结果JSON", null=True),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("video_path", models.CharField(blank=True, max_length=255, null=True)),
                ("dance_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.sysuser",
                    ),
                ),
            ],
            options={
                "db_table": "fitness_video_process_task",
                "ordering": ["-created_at"],
            },
        ),
    ]
