# Generated by Django 4.2.20 on 2026-05-11 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("fitness", "0006_videoprocesstask"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotatedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "video_path",
                    models.CharField(max_length=255, verbose_name="视频文件路径"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, help_text="处理进度 0-100"),
                ),
                ("message", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "total_frames",
                    models.IntegerField(default=0, verbose_name="视频总帧数"),
                ),
                ("fps", models.FloatField(default=0, verbose_name="视频帧率")),
                ("duration", models.FloatField(default=0, verbose_name="视频时长(秒)")),
                (
                    "frame_count",
                    models.IntegerField(default=0, verbose_name="已处理帧数"),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.sysuser",
                    ),
                ),
            ],
            options={
                "db_table": "fitness_annotated_video",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnotatedFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_index", models.IntegerField(verbose_name="帧序号(从0开始)")),
                ("timestamp", models.FloatField(verbose_name="该帧时间戳(秒)")),
                (
                    "landmarks",
                    models.TextField(
                        verbose_name="33个关键点数据JSON [x,y,z,visibility,...]"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=True, verbose_name="是否有效(检测到人体)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="fitness.annotatedvideo",
                    ),
                ),
            ],
            options={
                "db_table": "fitness_annotated_frame",
                "ordering": ["frame_index"],
                "unique_together": {("video", "frame_index")},
            },
        ),
    ]
